feat: add Namespace CLI via Github Releases
devcontainers-extra/features pull request #54
Opened 2024-10-15 08:37 UTC by pl4nty

Migrated from https://github.com/devcontainers-contrib/features/pull/591

2024-10-18 19:24 UTC, koralowiec requested changes
Thanks for the PR!
I left one change request

2024-10-18 19:24 UTC, koralowiec commented on test/namespace-cli/scenarios.json
Similarly to https://github.com/devcontainers-extra/features/pull/55, please add an additional test for a specific version ([comment](https://github.com/devcontainers-extra/features/pull/55/files#r1806929253))

2024-10-19 02:46 UTC, pl4nty commented on test/namespace-cli/scenarios.json
I've added a version test for the CLI itself, but the accompanying docker credential helper doesn't have a version indicator

2024-10-19 11:56 UTC, koralowiec commented on test/namespace-cli/scenarios.json
That's fine, if the helper doesn't expose version information, then we can skip it

2024-10-19 11:57 UTC, koralowiec approved these changes

2024-10-19 11:57 UTC, koralowiec commented
Let's merge it!

2024-10-19 11:57 UTC, merged